### ISSUE TITLE
Scope not supported: offline_access

### ISSUE THREAD

**Issue by rammkripa** [digita-ai/dgt-id-broker#419]
Scope not supported: offline_access Is the message I receive when trying to log in using the proxy with the upstream server as (oidc.signinwithethereum.org)

**Comment by AbelVandenBriel** [comment]
Hi @rammkripa, apologies for getting to your issue so late.

I don't know in what context you are using the proxy, but it is completely customisable. If you require the "offline_access" scope to login, you need to add it to the openid configuration document that you are using with the proxy.

Going to https://oidc.signinwithethereum.org/.well-known/openid-configuration shows that "offline_access" is indeed not a scope that is present on that upstream. The client that you're trying to login with seems to want to use that scope, eventhough it is not available. If you are in control of the client you should simply not request that scope.

Since this is not an issue with our proxy, I will close this issue.
